### ISSUE TITLE
TODO: consegna finale v1.1

### ISSUE THREAD

**Issue by saccarosium** [Friedchicken-42/progettoIngegneriaSoftware#17]
- [x] Migliorare la UI @saccarosium
  - [x] Migliorare palette
- [x] Riaggiornare documenti @LucaBarban
  - [x] UML
  - [x] Feauters
  - [x] Aggiorna todolist con cose nuove
  - [x] Facciamo scheduling delle notifiche 7 giorni prima invece che 2
- [x] Prenota esame @saccarosium 
- [x] Migliorare gestione notifiche @saccarosium
- [x] Rilettura documenti @LucaBarban @Friedchicken-42 
- [ ] Caricare documenti consegna su github @saccarosium
- [x] Fai vedere errore quando cè un problema con il manager @Friedchicken-42

**Comment by LucaBarban** [comment]
Possibili cose da ricorntrollare:
- D3, lasciare o meno le questioni aperte
- D3 S03 sistemare il testo per renderlo al pari delle funzionalità dell'app
- D5 rifare diagramma delle classi prendendo le classi aggiornate
- D5 aggiornare gli screenshot dell'app (?)
